/**:
  ros__parameters:
    frequency: 5.0
    surge:
      p_gain: 1.0
      i_gain: 0.1
      i_limit: 0.1
      d_gain: 1.0
    sway:
      p_gain: 1.0
      i_gain: 0.01
      i_limit: 0.1
      d_gain: 2.0
    yaw:
      p_gain: 2.0
      i_gain: 0.1
      i_limit: 0.1
      d_gain: 1.0