/**:
  ros__parameters:
    # Vessel physical dimensions (meters)
    vessel:
      length: 2.0    # Length of vessel (m)
      beam: 0.5      # Width of vessel (m)
      draft: 0.02    # Draft/depth of vessel (m)

    # Controller parameters
    control:
      # Position control gains
      p_gain:
        pos: 0.6     # Proportional gain for position
        vel: 0.2     # Proportional gain for velocity
        yaw: 0.7     # Proportional gain for yaw

      # Integral gains
      i_gain:
        pos: 0.05     # Integral gain for position
        vel: 0.0     # Integral gain for velocity
        yaw: 0.1     # Integral gain for yaw

      # Derivative gains
      d_gain:
        pos: 0.5     # Derivative gain for position
        vel: 0.5     # Derivative gain for velocity
        yaw: 1.5     # Derivative gain for yaw

      # Integral error limits
      max_integral_error:
        pos: 1.0     # Maximum position error integration
        yaw: 1.4     # Maximum yaw error integration

      # Saturation parameters
      saturation:
        pos: 0.1     # Position control saturation
        yaw: 0.1     # Yaw control saturation

      # Target reaching tolerances
      tolerance:
        pos: 0.25    # Position reaching tolerance (m)
        yaw: 0.1     # Yaw angle reaching tolerance (rad)

    # Reference filter parameters
    filter:
      omega: [0.15, 0.15, 0.15]  # Natural frequency for reference filter
      delta: [0.8, 0.8, 0.8]     # Damping ratio for reference filter

    # Performance metrics configuration
    metrics:
      window_size: 200    # Number of samples in moving window
      interval: 1.0       # Time between metrics calculations (seconds)

    # General parameters
    dt: 0.01              # Control loop time step (seconds)
