/**:
  ros__parameters:
    frequency: 40.0
    channels:

      esc_1:
        pwm_topic: hardware/prop/esc_1/pwm
        scaled_topic: hardware/prop/esc_1/scaled
        channel: 5
        pulse_duration:
          center: 1.50001
          max: 1.7
          min: 1.5
        scale:
          center: 0.0
          min: -1.0
          max: 1.0

      esc_2:
        pwm_topic: hardware/prop/esc_2/pwm
        scaled_topic: hardware/prop/esc_2/scaled
        channel: 7
        pulse_duration:
          center: 1.50001
          max: 1.7
          min: 1.5
        scale:
          center: 0.0
          min: -1.0
          max: 1.0

      esc_3:
        pwm_topic: hardware/prop/esc_3/pwm
        scaled_topic: hardware/prop/esc_3/scaled
        channel: 9
        pulse_duration:
          center: 1.50001
          max: 1.7
          min: 1.5
        scale:
          center: 0.0
          min: -1.0
          max: 1.0

      esc_4:
        pwm_topic: hardware/prop/esc_4/pwm
        scaled_topic: hardware/prop/esc_4/scaled
        channel: 11
        pulse_duration:
          center: 1.50001
          max: 1.7
          min: 1.5
        scale:
          center: 0.0
          min: -1.0
          max: 1.0

      esc_5:
        pwm_topic: hardware/prop/esc_5/pwm
        scaled_topic: hardware/prop/esc_5/scaled
        channel: 13
        pulse_duration:
          center: 1.50001
          max: 1.7
          min: 1.5
        scale:
          center: 0.0
          min: -1.0
          max: 1.0

      esc_6:
        pwm_topic: hardware/prop/esc_6/pwm
        scaled_topic: hardware/prop/esc_6/scaled
        channel: 15
        pulse_duration:
          center: 1.50001
          max: 1.7
          min: 1.5
        scale:
          center: 0.0
          min: -1.0
          max: 1.0
