/**:
  ros__parameters:
    frequency: 40.0
    channels:

      esc_1:
        pwm_topic: hardware/prop/esc_1/pwm
        scaled_topic: hardware/prop/esc_1/scaled
        channel: 0
        pulse_duration:
          center: 1.575
          max: 1.675
          min: 1.475
        scale:
          center: 0.0
          min: -1.3
          max: 1.3

      esc_2:
        pwm_topic: hardware/prop/esc_2/pwm
        scaled_topic: hardware/prop/esc_2/scaled
        channel: 1
        pulse_duration:
          center: 1.575
          max: 1.675
          min: 1.475
        scale:
          center: 0.0
          min: -1.0
          max: 1.0

      esc_3:
        pwm_topic: hardware/prop/esc_3/pwm
        scaled_topic: hardware/prop/esc_3/scaled
        channel: 3
        pulse_duration:
          center: 1.5
          min: 1.25
          max: 1.75
        scale:
          center: 0.0
          min: -1.0
          max: 1.0

      esc_4:
        pwm_topic: hardware/prop/esc_4/pwm
        scaled_topic: hardware/prop/esc_4/scaled
        channel: 5
        pulse_duration:
          center: 1.575
          max: 1.675
          min: 1.475
        scale:
          center: 0.0
          min: -1.3
          max: 1.3

      esc_5:
        pwm_topic: hardware/prop/esc_5/pwm
        scaled_topic: hardware/prop/esc_5/scaled
        channel: 4
        pulse_duration:
          center: 1.575
          max: 1.675
          min: 1.475
        scale:
          center: 0.0
          min: -1.0
          max: 1.0

      esc_6:
        pwm_topic: hardware/prop/esc_6/pwm
        scaled_topic: hardware/prop/esc_6/scaled
        channel: 3
        pulse_duration:
          center: 1.5
          min: 1.25
          max: 1.75
        scale:
          center: 0.0
          min: -1.0
          max: 1.0
