/**:
  ros__parameters:
    thrusters:

      bow_port:
        type: azimuth
        force_topic: thruster/bow_port/command
        force_max: 1.0
        force_min: 0.0
        rpm:
          topic: hardware/prop/esc_1/scaled
          inverted: false
        angle:
          topic: hardware/joint/servo_1/angle
          inverted: false

      bow_center:
        type: azimuth
        force_topic: thruster/bow_center/command
        force_max: 1.0
        force_min: 0.0
        rpm:
          topic: hardware/prop/esc_2/scaled
          inverted: false
        angle:
          topic: hardware/joint/servo_2/angle
          inverted: false

      bow_starboard:
        type: azimuth
        force_topic: thruster/bow_starboard/command
        force_max: 1.0
        force_min: 0.0
        rpm:
          topic: hardware/prop/esc_3/scaled
          inverted: false
        angle:
          topic: hardware/joint/servo_3/angle
          inverted: false

      stern_port:
        type: azimuth
        force_topic: thruster/stern_port/command
        force_max: 1.0
        force_min: 0.0
        rpm:
          topic: hardware/prop/esc_4/scaled
          inverted: false
        angle:
          topic: hardware/joint/servo_5/angle
          inverted: false

      stern_center:
        type: azimuth
        force_topic: thruster/stern_center/command
        force_max: 1.0
        force_min: 0.0
        rpm:
          topic: hardware/prop/esc_5/scaled
          inverted: false
        angle:
          topic: hardware/joint/servo_6/angle
          inverted: false

      stern_starboard:
        type: azimuth
        force_topic: thruster/stern_starboard/command
        force_max: 1.0
        force_min: 0.0
        rpm:
          topic: hardware/prop/esc_6/scaled
          inverted: false
        angle:
          topic: hardware/joint/servo_4/angle
          inverted: false
