services:
  voyager:
    image: docker.io/incebellipipo/cybership:humble
    profiles: ["voyager"]
    build:
      args:
        - ROS_DISTRO=humble
      context: .
      dockerfile: dockerfile
    command: |
      source /ros/install/setup.bash
      ros2 launch cybership_bringup voyager.launch.py vessel_name:=voyager
    network_mode: host
    volumes:
      - /dev:/dev
      - ./cybership_config/config:/ros/install/cybership_config/share/cybership_config/config
    privileged: true
    restart: always

  enterprise:
    image: docker.io/incebellipipo/cybership-enterprise:humble
    profiles: ["enterprise"]
    build:
      context: .
      dockerfile: dockerfile
      args:
        - ROS_DISTRO=humble
    command: |
      source /ros/install/setup.bash
      ros2 launch cybership_bringup enterprise.launch.py vessel_name:=enterprise
    network_mode: host
    volumes:
      - /dev:/dev
      - ./cybership_config/config/enterprise:/ros/install/cybership_config/share/cybership_config/config/enterprise
    privileged: true
    restart: always