version: '3'

services:
  cybership:
    build:
      context: .
      dockerfile: Dockerfile.raspi
    command: /bin/bash -c 'source /ros/install/setup.bash ; ros2 launch cybership_bringup enterprise1.launch.py'
    network_mode: host
    volumes:
      - /dev:/dev
    privileged: true