servo_driver_node:
  ros__parameters:
    frequency: 50.0
    channels:
      bow_thruster:
        pwm_topic: cybership/servo/pwm/bow_thruster
        scaled_topic: cybership/servo/scaled/bow_thruster
        channel: 0
        center: 1.3
        min: 1.0
        max: 1.6
      vsp_1:
        pwm_topic: cybership/servo/pwm/vsp_1
        scaled_topic: cybership/servo/scaled/vsp_1
        channel: 1
        center: 1.0
        min: 1.0
        max: 1.5
      vsp_2:
        pwm_topic: cybership/servo/pwm/vsp_2
        scaled_topic: cybership/servo/scaled/vsp_2
        channel: 2
        center: 1.0
        min: 1.0
        max: 1.5
      servo_1:
        pwm_topic: cybership/servo/pwm/servo_1
        scaled_topic: cybership/servo/scaled/servo_1
        channel: 3
        center: 1.05
        max: 1.25
        min: 0.85
      servo_3:
        pwm_topic: cybership/servo/pwm/servo_3
        scaled_topic: cybership/servo/scaled/servo_3
        channel: 4
        min: 1.03
        center: 1.2
        max: 1.42
      servo_2:
        pwm_topic: cybership/servo/pwm/servo_2
        scaled_topic: cybership/servo/scaled/servo_2
        channel: 5
        center: 1.05
        min: 0.86
        max: 1.2
      servo_4:
        pwm_topic: cybership/servo/pwm/servo_4
        scaled_topic: cybership/servo/scaled/servo_4
        channel: 6
        center: 1.05
        min: 0.95
        max: 1.24
