enterprise1_thruster_node:
  ros__parameters:
    thrusters:
      vsp_port:
        type: vsp
        force_topic: /CSEI/thrusters/port/command
        force_max: 1.0
        force_min: -1.0
        arm_x:
          topic: /CSEI/hardware/servo/servo_3/scaled
          inverted: false
        arm_y:
          topic: /CSEI/hardware/servo/servo_1/scaled
          inverted: false
        rpm:
          topic: /CSEI/hardware/servo/vsp_1/scaled
          cmd: 0.4

      vsp_starboard:
        type: vsp
        force_topic: /CSEI/thrusters/starboard/command
        force_max: 1.0
        force_min: -1.0
        arm_x:
          topic: /CSEI/hardware/servo/servo_2/scaled
          inverted: false
        arm_y:
          topic: /CSEI/hardware/servo/servo_4/scaled
          inverted: false
        rpm:
          topic: /CSEI/hardware/servo/vsp_2/scaled
          cmd: 0.4
