enterprise1_thruster_node:
  ros__parameters:
    vsp_port:
      type: vsp
      force_topic: /CSEI/thrusters/port/command
      arm_x:
        topic: /CSEI/hardware/servo/servo_1/scaled
        inverted: true
      arm_y:
        topic: /CSEI/hardware/servo/servo_3/scaled
        inverted: true

    vsp_starboard:
      type: vsp
      arm_x:
        topic: /CSEI/hardware/servo/servo_4/scaled
        inverted: false
      arm_y:
        topic: /CSEI/hardware/servo/servo_2/scaled
        inverted: false

    tunnel_bow:
      type: fixed
      control:
        topic: /CSEI/hardware/servo/bow_thruster/scaled
        inverted: false
