/**:
  ros__parameters:
    frequency: 50.0
    channels:
      esc_0:
        pwm_topic: /CSEI/hardware/servo/esc_0/pwm
        scaled_topic: /CSEI/hardware/servo/esc_0/scaled
        channel: 0
        pulse_duration:
          center: 1.3
          min: 1.15
          max: 1.45
        scale:
          center: 0.0
          min: -1.0
          max: 1.0
      esc_1:
        pwm_topic: /CSEI/hardware/servo/esc_1/pwm
        scaled_topic: /CSEI/hardware/servo/esc_1/scaled
        channel: 1
        pulse_duration:
          center: 1.0
          min: 0.9
          max: 1.1
        scale:
          center: 0.0
          min: -1.0
          max: 1.0
      esc_2:
        pwm_topic: /CSEI/hardware/servo/esc_2/pwm
        scaled_topic: /CSEI/hardware/servo/esc_2/scaled
        channel: 2
        pulse_duration:
          center: 1.0
          min: 0.9
          max: 1.1
        scale:
          center: 0.0
          min: -1.0
          max: 1.0
