/**:
  ros__parameters:
    thrusters:
      azimuth_port:
        type: azimuth
        force_topic: /CSEI/thrusters/port/command
        force_max: 1.0
        force_min: -1.0

      azimuth_port:
        type: azimuth
        force_topic: /CSEI/thrusters/starboard/command
        force_max: 1.0
        force_min: -1.0

      tunnel:
        type: fixed
        force_max: 0.5
        force_min: -0.5
        force_topic: /CSEI/thrusters/tunnel/command
        signal:
          topic:
          inverted: false