/**:
  ros__parameters:
    allocation:
      type: topic
      interface_type: geometry_msgs/msg/Twist
      topic_name: control/velocity/command
      deadman_buttons: [9]
      axis_mappings:
        linear-x:
          axis: 1
          scale: 1.0
          offset: 0.0
        linear-y:
          axis: 0
          scale: 1.0
          offset: 0.0
        angular-z:
          axis: 3
          scale: 1.0
          offset: 0.0

    enable:
      type: service
      interface_type: std_srvs/srv/Empty
      service_name: thruster/enable
      buttons: [0]


    disable:
      type: service
      interface_type: std_srvs/srv/Empty
      service_name: thruster/disable
      buttons: [1]
