/**:
  ros__parameters:
    hardware:
      port: /dev/ttyUSB0
      baudrate: 57600
    servos:
      # Starboard
      servo_1:
        frame_id: starboard_azimuth_link
        control_topic: hardware/joint/servo_1/angle
        device_id: 1
        gain: 100.0
        delta: 45.0
        offset: -3.0
      # Port
      servo_2:
        frame_id: port_azimuth_link
        control_topic: hardware/joint/servo_2/angle
        device_id: 2
        gain: 100.0
        delta: 45.0
        offset: 0.18