/**:
  ros__parameters:
    frequency: 50.0
    channels:
      # Tunnel thruster
      esc_0:
        pwm_topic: hardware/prop/esc_0/pwm
        scaled_topic: hardware/prop/esc_0/scaled
        channel: 0
        pulse_duration:
          center: 1.5
          min: 1.25
          max: 1.75
        scale:
          center: 0.0
          min: -1.0
          max: 1.0
      # Starboard
      esc_1:
        pwm_topic: hardware/prop/esc_1/pwm
        scaled_topic: hardware/prop/esc_1/scaled
        channel: 1
        pulse_duration:
          center: 1.5
          min: 1.35
          max: 1.65
        scale:
          center: 0.0
          min: -1.0
          max: 1.0
      # Port
      esc_2:
        pwm_topic: hardware/prop/esc_2/pwm
        scaled_topic: hardware/prop/esc_2/scaled
        channel: 2
        pulse_duration:
          center: 1.5
          min: 1.35
          max: 1.65
        scale:
          center: 0.0
          min: -1.0
          max: 1.0
