/**:
  ros__parameters:
    thrusters:
      azimuth_port:
        type: azimuth
        force_topic: /voyager/thrusters/port/command
        force_max: 1.0
        force_min: -1.0
        rpm:
          topic: /voyager/hardware/prop/esc_2/scaled
          inverted: false
        angle:
          topic: /voyager/hardware/joint/servo_2/angle
          inverted: false

      azimuth_starboard:
        type: azimuth
        force_topic: /voyager/thrusters/starboard/command
        force_max: 1.0
        force_min: -1.0
        rpm:
          topic: /voyager/hardware/prop/esc_1/scaled
          inverted: false
        angle:
          topic: /voyager/hardware/joint/servo_1/angle
          inverted: false

      tunnel:
        type: fixed
        force_max: 1.0
        force_min: -1.0
        force_topic: /voyager/thrusters/tunnel/command
        signal:
          topic: /voyager/hardware/prop/esc_0/scaled
          inverted: false