/**:
  ros__parameters:
    thrusters:
      azimuth_port:
        type: azimuth
        force_topic: thruster/port/command
        force_max: 1.0
        force_min: -1.0
        rpm:
          topic: hardware/prop/esc_2/scaled
          inverted: false
        angle:
          topic: hardware/joint/servo_2/angle
          inverted:  true

      azimuth_starboard:
        type: azimuth
        force_topic: thruster/starboard/command
        force_max: 1.0
        force_min: -1.0
        rpm:
          topic: hardware/prop/esc_1/scaled
          inverted: false
        angle:
          topic: hardware/joint/servo_1/angle
          inverted: true

      tunnel:
        type: fixed
        force_max: 1.0
        force_min: -1.0
        force_topic: thruster/tunnel/command
        signal:
          topic: hardware/prop/esc_0/scaled
          inverted: true