/**:
  ros__parameters:
    thrusters:
      vsp_port:
        type: vsp
        force_topic: /enterprise/thrusters/port/command
        force_max: 1.0
        force_min: -1.0
        arm_x:
          topic: /enterprise/hardware/servo/servo_3/scaled
          inverted: true
        arm_y:
          topic: /enterprise/hardware/servo/servo_1/scaled
          inverted: true
        rpm:
          topic: /enterprise/hardware/servo/vsp_1/scaled
          cmd: 0.4

      vsp_starboard:
        type: vsp
        force_topic: /enterprise/thrusters/starboard/command
        force_max: 1.0
        force_min: -1.0
        arm_x:
          topic: /enterprise/hardware/servo/servo_2/scaled
          inverted: true
        arm_y:
          topic: /enterprise/hardware/servo/servo_4/scaled
          inverted: true
        rpm:
          topic: /enterprise/hardware/servo/vsp_2/scaled
          cmd: 0.0

      tunnel:
        type: fixed
        force_max: 0.5
        force_min: -0.5
        force_topic: /enterprise/thrusters/tunnel/command
        signal:
          topic: /enterprise/hardware/servo/bow_thruster/scaled
          inverted: false